M48
; DRILL file {KiCad 7.0.10} date Wed Jan 31 18:26:44 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-31T18:26:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0433
%
G90
G05
T1
X3.3Y-2.4
X3.3Y-2.6
X5.2Y-2.4
T2
X3.7Y-2.4
X3.7Y-2.6
X3.7Y-2.8
X4.1Y-2.4
X4.1Y-2.6
X4.1Y-2.8
X4.7Y-2.4
X5.1Y-2.4
T3
X3.4Y-2.4
X3.4Y-2.6
X3.4Y-2.8
X3.5Y-2.4
X3.5Y-2.6
X3.5Y-2.8
T4
X5.3Y-2.3
X5.3Y-2.4
X5.3Y-2.5
X5.3Y-2.6
X5.3Y-2.7
X5.3Y-2.8
X5.4Y-2.3
X5.4Y-2.4
X5.4Y-2.5
X5.4Y-2.6
X5.4Y-2.7
X5.4Y-2.8
T5
X4.272Y-2.3114
X4.272Y-2.4886
X4.528Y-2.3114
X4.528Y-2.4886
M30
